# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

use_frameworks!

def project_pods
  # Pods for CTA
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Storage'
  pod 'Kingfisher'
end

target 'CTA' do
  project_pods
end
target 'CTATests' do
  project_pods
end
